---
# frontend tasks
- name: Install haproxy
  yum:
    name: haproxy
    state: latest

- name: Install httpie
  yum:
    name: python-httpie
    state: latest

- name: Configure HAProxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify:
    - restart haproxy

- name: enable HAProxy
  service:
    name: haproxy
    state: started
